[package]
name = "bls-signatures"
description = ""
version = "1.2.5"
edition = "2021"

[features]
legacy = []
bip32 = []
use_serde = ["serde"]
rubas_helpers = ["rand"]
default = [ "legacy", "bip32", "rubas_helpers", "use_serde"]
apple = ["bls-rubas-sys/apple"]

[dependencies]
bls-rubas-sys = { path = "../bls-rubas-sys" }
serde = { version= "1.0.160", features = ["derive"], optional = true}
rand = { version= "0.8.5", optional = true}
hex = { version = "0.4.3"}
