#!/usr/bin/env bash
#
#  rubasd The Rubas Core server.
#
#
# chkconfig: 345 80 20
# description: rubasd
# processname: rubasd
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/rubasd, see below
if [ -f /etc/sysconfig/rubasd ]; then
        . /etc/sysconfig/rubasd
fi

RETVAL=0

prog=rubasd
# you can override the lockfile via BITCOIND_LOCKFILE in /etc/sysconfig/rubasd
lockfile=${BITCOIND_LOCKFILE-/var/lock/subsys/rubasd}

# rubasd defaults to /usr/bin/rubasd, override with BITCOIND_BIN
rubasd=${BITCOIND_BIN-/usr/bin/rubasd}

# rubasd opts default to -disablewallet, override with BITCOIND_OPTS
rubasd_opts=${BITCOIND_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $rubasd $rubasd_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
